### ISSUE TITLE
协程视频地址错误，少了个 / ,因为家里网络不好，不能pullrequest, 所以issue形式提交

### ISSUE THREAD

**Issue by chenye2017** [easy-swoole/doc-old#299]
https://www.easyswoole.com/play_video.html?video=aHR0cDovL3ZpZGVvLW9zcy5lYXN5c3dvb2xlLmNvbS8lRTUlODUlQTUlRTklOTclQTglRTYlOTUlOTklRTclQTglOEIxLyVFNSU4RCU4RiVFNyVBOCU4QiVFNyVBRSU4MCVFNCVCQiU4Qi5tcDQ=

**Comment by kiss291323003** [comment]
感谢反馈，已经处理
